version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: html
          overwrite: true
          to: 's3://carktube.com'
orbs:
  aws-s3: circleci/aws-s3@1.0.15
